---
galaxy_info:
  author: wangrin
  namespace: wangrin
  role_name: postgresql
  description: Installation et configuration de PostgreSQL
  company: ""
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
